# Generated by Django 3.1.5 on 2021-02-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('name', models.TextField()),
                ('shares', models.IntegerField()),
                ('avgCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('mktVal', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('gain', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('pctGain', models.DecimalField(decimal_places=4, default=0.0, max_digits=1000)),
            ],
        ),
    ]
