# Generated by Django 3.1.5 on 2021-02-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='pctGain',
        ),
        migrations.AddField(
            model_name='stock',
            name='dates',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='stock',
            name='eps',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='stock',
            name='history',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='stock',
            name='pe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='stock',
            name='prices',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.TextField(default=''),
        ),
    ]
