# Generated by Django 3.1.5 on 2021-02-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210205_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='pctGain',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
