# Generated by Django 3.1.5 on 2021-02-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210205_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='pctGainFormatted',
            field=models.TextField(default=''),
        ),
    ]
