# Generated by Django 3.1.5 on 2021-02-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20210207_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='perfTodayFormatted',
            field=models.TextField(default=''),
        ),
    ]
