# Generated by Django 3.1.5 on 2021-02-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_stock_perftodayformatted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
