# Generated by Django 3.1.5 on 2021-02-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20210207_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(default='')),
                ('pres1', models.TextField(default='')),
                ('pres2', models.TextField(default='')),
                ('pres3', models.TextField(default='')),
            ],
        ),
    ]
