# Generated by Django 3.1.5 on 2021-03-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='link1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='link2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='link3',
            field=models.TextField(default=''),
        ),
    ]
