# Generated by Django 3.1.5 on 2021-03-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20210316_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='link1',
            field=models.TextField(default='#'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='link2',
            field=models.TextField(default='#'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='link3',
            field=models.TextField(default='#'),
        ),
    ]
