# Generated by Django 3.1.5 on 2021-03-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20210316_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='pop1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='pop2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='pop3',
            field=models.BooleanField(default=False),
        ),
    ]
